name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm ci
      - name: Test
        run: npm test

  start:
    runs-on: ubuntu-latest
    needs: [ lint, test ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: npm install
      - name: Start
        run: npm start
